// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX8xu3OkmeqHbdbsrWn8UydqpoaXJmHPc',
    appId: '1:488766537138:web:b645525c4cc6a32582b8ab',
    messagingSenderId: '488766537138',
    projectId: 'chat-app-d275a',
    authDomain: 'chat-app-d275a.firebaseapp.com',
    storageBucket: 'chat-app-d275a.appspot.com',
    measurementId: 'G-NH9733RFTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfQVx93V6iwS0hJaA-PH2vU9bdQIII8KY',
    appId: '1:488766537138:android:8eb4fd33ae69af6e82b8ab',
    messagingSenderId: '488766537138',
    projectId: 'chat-app-d275a',
    storageBucket: 'chat-app-d275a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG04raFTluJ5RTYxzxNmT6rNAawoeK9qg',
    appId: '1:488766537138:ios:69da8b45562f1fb382b8ab',
    messagingSenderId: '488766537138',
    projectId: 'chat-app-d275a',
    storageBucket: 'chat-app-d275a.appspot.com',
    iosBundleId: 'com.example.chatApp1',
  );
}
